### ISSUE TITLE
worli2.0 requires on mkfs.fat but doesn't check if it's installed

### ISSUE THREAD

**Issue by techflashYT** [buddyjojo/worli#11]
On a fresh system, without mkfs.fat installed, worli2.0 says that all dependencies are good, but yet blows up in the abscense of mkfs.fat.
I may make a PR fixing this soon, but just having it here for reporting sake.

**Comment by buddyjojo** [comment]
Huh

**Comment by buddyjojo** [comment]
There
Entirely untested so open the issue again if it doesn't look right
