### ISSUE TITLE
[ERROR] 'batchexec.exe' does not exist.

### ISSUE THREAD

**Issue by MohammadRHashem** [buddyjojo/worli#7]
this is the error i get when running the script (worli2.0.sh)..
even though i have:
-files/batchexe.exe
-files/batchexec.c
-files/BCD
-files/gptpatch.img
-files/worlipe-no-re.cmd
-files/worlipe.cmd

and in tmp dir there exist :
file:///tmp/worli/batchexe.exe
file:///tmp/worli/BCD
file:///tmp/worli/bootaa64.efi
file:///tmp/worli/ntfs_aa64.efi
file:///tmp/worli/pe-files.zip
file:///tmp/worli/UEFI_Firmware.zip
file:///tmp/worli/Windows_ARM64_Drivers.zip
file:///tmp/worli/worlipe.cmd

so whats the point?

**Comment by MohammadRHashem** [comment]
i see the batchexec.c instead of ext (.exe) ....

**Comment by buddyjojo** [comment]
Are you manually downloading the files or using the auto download option?

**Comment by MohammadRHashem** [comment]
> Are you manually downloading the files or using the auto download option?

yep

**Comment by buddyjojo** [comment]
Ah I think I see the problem here.
The script is looking for "batchexec.exe" but in the repo files I named it "batchexe.exe" by mistake.
Will fix.

**Comment by MohammadRHashem** [comment]
great then ill wait the new commit 👍🏼
Thx :)

**Comment by buddyjojo** [comment]
Ok should be fixed.
I also noticed that the release was pretty outdated so please download the script again.
