### ISSUE TITLE
mkfs.fat: unable to open /dev/mmcblk01: No such file or directory

### ISSUE THREAD

**Issue by MohammadRHashem** [buddyjojo/worli#8]
[log.txt](https://github.com/buddyjojo/worli/files/11894246/log.txt)
This is the full script log, donno what's the prob but probably another bug 😆

**Comment by MohammadRHashem** [comment]
tried with different sd cards, no luck 
idk if it does error when installing on usb devices

**Comment by buddyjojo** [comment]
Ah darn, old bug I didn't fix in this branch.
Again will fix.

**Comment by buddyjojo** [comment]
Ok try now (with the script downloaded directly from the repo, not the release).

**Comment by MohammadRHashem** [comment]
So far it worked  ! 
Testing to flash an sdcard and now it's copying files, if I close this issue then it works as a charm 🤝🏼
